version: "2"
services:
  rails_test:
    container_name: rails_test
    image: "registry.sorice.info/rails-test:1.1"
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    command: sh
    volumes:
      - ./projects:/projects
    ports:
     - 12398:3000